### ISSUE TITLE
No module named 'PNGFile'

### ISSUE THREAD

**Issue by mrme44** [philadams-zz/dimensions#3]
When I tried to import dimensions, I got this error message. I'm using python 3.4 on windows 7.

Traceback (most recent call last):
  File "G:\site\gallery\gen_code.py", line 1, in <module>
    import os, dimensions
  File "C:\Python34\lib\site-packages\dimensions__init__.py", line 1, in <modul
e>
    from .core import dimensions, cli
  File "C:\Python34\lib\site-packages\dimensions\core.py", line 15, in <module>
    import PNGFile
ImportError: No module named 'PNGFile'

**Comment by anirudhvoruganti96** [comment]
I faced the same problem. But, worked  when tried with Python 2.7.

Just try,  pip install dimensions. and then import dimensions into your Python 2.7 code
